[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
lexer = { path = "../crates/lexer" }
clap = { version = "4.3", features = ["derive"] }

[[bin]]
name = "hydrac"
path = "src/main.rs"
